---
# sets up scherzo on a server

- name: Copy scherzo config
  copy:
    src: config.toml
    dest: /var/lib/scherzo/config.toml

- name: Deploy scherzo docker
  docker_container:
    image: "yusdacra/scherzo:{{ scherzo_docker_tag }}"
    name: "scherzo"
    state: "started"
    volumes:
      - "/var/lib/scherzo/db:/srv/scherzo/db"
      - "/var/lib/scherzo/media:/srv/scherzo/media"
      # inject configs here
      - "/var/lib/scherzo/config.toml:/srv/scherzo/config.toml"
      - "/var/lib/scherzo/email_creds.toml:/srv/scherzo/email_creds.toml"
    log_driver: "journald"
    ports: ["2289:2289"]
